# Copyright (C) 2016 Google Inc.
# Licensed under http://www.apache.org/licenses/LICENSE-2.0 <see LICENSE file>

---

- name: Add NodeJS repository
  command: bash -c "curl -sL https://deb.nodesource.com/setup_5.x | sudo -E bash -"

- name: update apt
  sudo: yes
  apt:
    update_cache: yes
    cache_valid_time: 3600
