# # Copyright (C) 2016 Google Inc.
# Licensed under http://www.apache.org/licenses/LICENSE-2.0 <see LICENSE file>
#
# See https://developers.google.com/appengine/docs/python/config/appconfig

application: local
version: 1
runtime: python27
api_version: 1
threadsafe: true
instance_class: B4
manual_scaling:
  instances: 4

handlers:
  - url: /login
    script: ggrc.app.app.wsgi_app
    login: required
    secure: always

  - url: /_background_tasks/.*
    script: ggrc.app.app.wsgi_app
    login: admin
    secure: always

  - url: /notify_emaildigest
    script: ggrc.app.app.wsgi_app
    login: admin
    secure: always

#  - url: /notify_email_deferred
#    script: ggrc.app.app.wsgi_app
#    login: admin
#    secure: always

  - url: /.*
    script: ggrc.app.app.wsgi_app
    secure: always

libraries:
  - name: MySQLdb
    version: "latest"
  - name: jinja2
    version: "2.6"

builtins:
- remote_api: on

# Don't upload some files
#  - note the first 9 items are defaults, see:
#    https://developers.google.com/appengine/docs/python/config/appconfig#Skipping_Files
skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?app\.yml
- ^(.*/)?index\.yaml
- ^(.*/)?index\.yml
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*
# Custom GGRC excludes here
- requirements\.txt
- requirements\.txt\.md5
- requirements-dev\.txt
- requirements-selenium\.txt
- migrations/.*
- tests/.*
- service_specs/.*
- assets/.*
- reports/.*

# Define certain environment variables
env_variables:
  GGRC_SETTINGS_MODULE: "development app_engine ggrc_basic_permissions.settings.development ggrc_risks.settings.development ggrc_risk_assessments.settings.development ggrc_workflows.settings.development"
  GGRC_DATABASE_URI: "mysql+mysqldb://root:root@localhost/ggrcdev?charset=utf8"
  GGRC_SECRET_KEY: "Something-secret"
  GGRC_GOOGLE_ANALYTICS_ID: ""
  GGRC_GOOGLE_ANALYTICS_DOMAIN: ""
  GGRC_GAPI_KEY: "<Google Browser Key>"
  GGRC_GAPI_CLIENT_ID: "<Google OAuth Client ID>"
  GGRC_GAPI_CLIENT_SECRET: "<Google OAuth Client Secret>"
  GGRC_GAPI_ADMIN_GROUP: "<Google Group Email Address>"
  GGRC_BOOTSTRAP_ADMIN_USERS: "user@example.com"
  GGRC_RISK_ASSESSMENT_URL: "http://localhost:8080"
  APPENGINE_EMAIL: ""
  GGRC_CUSTOM_URL_ROOT: ""
  GGRC_ABOUT_URL: "#"
  GGRC_ABOUT_TEXT: "About gGRC"
  GGRC_EXTERNAL_HELP_URL: "#set_GGRC_EXTERNAL_HELP_URL_env_var"
  MAX_INSTANCES: "4"
  AUTHORIZED_DOMAINS: ""
