# Copyright (C) 2016 Google Inc.
# Licensed under http://www.apache.org/licenses/LICENSE-2.0 <see LICENSE file>

---
galaxy_info:
  author: Goran Mekić
  description: gGRC
  company: Reciprocity
dependencies:
  - {role: mysql}
